# Core Colors
background            #0f1511
foreground            #dee4de
selection_foreground  #8dd5b2
selection_background  #003825
cursor                #8dd5b2
cursor_text_color     #0f1511

# Regular Colors
color0  #0f1511
color1  #ffb4ab
color2  #8dd5b2
color3  #a5ccde
color4  #a9f2cd
color5  #cfe9d9
color6  #b4ccbd
color7  #dee4de

# Bright Colors
color8  #353b37
color9  #ffb4ab
color10 #8dd5b2
color11 #a5ccde
color12 #a9f2cd
color13 #cfe9d9 
color14 #b4ccbd
color15 #dee4de
