[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "Victor Mono"
style = "Medium Oblique"

[window]
dynamic_padding = false
decorations = "None"
startup_mode = "Maximized"
opacity = 0.95
blur = true

[window.padding]
x = 40
y = 40

[selection]
save_to_clipboard = true

[colors.primary]
background = "#000000"  # Deep black background, like a night sky
foreground = "#f0f0f0"  # Light gray for readability against the dark

[colors.cursor]
text = "#000000"       # Black cursor text
cursor = "#FFFF00"       # Bright yellow cursor - like a streetlight

[colors.normal]
black   = "#404040"       # Dark gray, like shadows between buildings
red     = "#FF4136"       # Bright red, like neon signs
green   = "#2ECC40"       # Vivid green, representing some natural element fighting through the city
yellow  = "#FFDC00"       # Intense yellow, like taxi lights
blue    = "#0074D9"       # Strong blue, like distant skyscrapers
magenta = "#F012BE"       # Hot pink, like club signs
cyan    = "#7FDBFF"       # Sky blue, representing the night sky reflecting on buildings
white   = "#A9A9A9"       # Light gray, like the moon or streetlights

[colors.bright]
black   = "#707070"       # Medium gray
red     = "#FF851B"       # Strong orange
green   = "#3D9970"       # Muted green
yellow  = "#FFEC3D"       # Brighter yellow
blue    = "#39CCCC"       # Turquoise
magenta = "#B10DC9"       # Dark purple
cyan    = "#8EE7FF"       # Pale blue
white   = "#FFFFFF"       # Pure white
