#!/bin/sh

VAULT_DIR="$HOME/Vaults/work/"

if ! tmux ls &> /dev/null; then
    echo "No tmux server running. Starting new tmux session 'sim-sim'."
    tmux new-session -s sim-sim -d

    tmux send-keys -t sim-sim "cd $VAULT_DIR" C-m
    tmux send-keys -t sim-sim "nvim -c 'e notes/to-do.md'" C-m

    tmux attach -t sim-sim
else
    if tmux ls | grep -q "sim-sim"; then
        if [ "$TMUX" ]; then
            tmux switch-client -t sim-sim
        else
            tmux attach -t sim-sim
        fi
    else
        tmux new-session -s sim-sim -d

        tmux send-keys -t sim-sim "cd $VAULT_DIR" C-m
        tmux send-keys -t sim-sim "nvim -c 'e notes/to-do.md'" C-m

        if [ -n "$TMUX" ]; then
            tmux switch-client -t sim-sim
        else
            tmux attach -t sim-sim
        fi
    fi
fi

